[platform]
display_name = Telegram
name = telegram
; proto_id: 0 = OAuth2, 1 = PNBA
proto_id = 1
; cat_id: 0 = Email, 1 = Message, 2 = Text, 3 = Bridge
cat_id = 1
auth_provider = self
; true or false
supports_offline_first = false
icon_svg = https://raw.githubusercontent.com/smswithoutborders/telegram-pnba-adapter/main/icons/telegram.svg
icon_png = https://raw.githubusercontent.com/smswithoutborders/telegram-pnba-adapter/main/icons/telegram.png

[author]
name = Afkanerd Developers
email = developers@smswithoutborders.com
